version: "3.8"
services:

  nginx:
    tty: true
    image: nginx:1.21-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client

  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: KAICHOKU_CONNECT
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    expose:
      - 3306 #不要かも？
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #DB駆動エントリポイント
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
      - ./mysql/conf.d:/etc/mysql/conf.d #MySql設定ファイル
    command: --default-authentication-plugin=mysql_native_password

  # Nest.jsサーバー
  server:
    tty: true
    build: 
      context: ./dockerfiles
      dockerfile: server.Dockerfile
    container_name: server
    command: 'nest start --watch'
    volumes:
     - ./server:/usr/src/app
     - ./types:/usr/src/types #共通型定義ファイル
    ports:
      - "3018:3018"
    depends_on:
      - db

  # Next.jsクライアント・サーバー
  client:
    build:
      context: ./dockerfiles
      dockerfile: client.Dockerfile
    container_name: web
    volumes:
      - ./client:/usr/src/app
      - ./types:/usr/src/types #共通型定義ファイル
    command: 'yarn dev'
    ports:
      - "3000:3000"
    depends_on:
      - server