version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: KAICHOKU_CONNECT
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
      - ./mysql/conf.d:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./client/src:/usr/src/app
    command: 'yarn dev'
    ports:
      - "3000:3000"
    depends_on:
      - db

  server:
    tty: true
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    command: 'nest start'
    volumes:
     - ./server/nest:/usr/src/app
    ports:
      - "3018:3018"
    depends_on:
      - db